### ISSUE TITLE
bad links on individual ephemeris pages at pypi

### ISSUE THREAD

**Issue by uhoh-SE** [brandon-rhodes/python-jplephem#17]
Not sure where to mention this, not sure of level of importance either:

on these pages (possibly others): 
    https://pypi.python.org/pypi/de405
    https://pypi.python.org/pypi/de406

There is a broken link to Standish (1998) PDF which looks like this:
    http://iau-comm4.jpl.nasa.gov/de405iom/de405iom.pdf

I found a copy of a similar named PDF here:
    ftp://ssd.jpl.nasa.gov/pub/eph/planets/ioms/de405.iom.pdf

SImilar situation here:
    https://pypi.python.org/pypi/de421

**Comment by brandon-rhodes** [comment]
Drat. They have been moving their PDFs around. :)

I will see about getting it fixed. Although hopefully no one is using those packages any more?

**Comment by uhoh-SE** [comment]
Right! :)

**Comment by brandon-rhodes** [comment]
I have update the repository and run `setup.py register` on all four of the ephemerides with broken links. Thanks for letting me know they were broken!
