### ISSUE TITLE
Comparison with JPL Horizons

### ISSUE THREAD

**Issue by Tarlan0001** [brandon-rhodes/python-jplephem#23]
In comparison with the data from JPL Horizons it gives some error:

```
JPL: [-1.10659532e+08  9.70047434e+07 -2.39525979e+04]
JL:   [-1.10369890e+08  8.93069592e+07  3.86931886e+07]
```
Hovewer in the documentation it's stated that `The package's test suite uses test files provided by JPL to confirm that the results are correct.`

The code:
```
using JPLEphemeris

spk = SPK("de430.bsp")
jd = parse(Float64,"2457388.33750")
st = state(spk, 0, 3, [jd])
```

**Comment by Tarlan0001** [comment]
The problem was in chosen coordinate system. The issue may be closed.

**Comment by brandon-rhodes** [comment]
Thanks for following up once you discovered the reason for the difference!
