### ISSUE TITLE
Extract data type 2 raw coefficients

### ISSUE THREAD

**Issue by ChristopherRabotin** [brandon-rhodes/python-jplephem#28]
What would be the best approach to extract the raw coefficients in a data type 2 BSP file?

Thanks

**Comment by brandon-rhodes** [comment]
Good question! There's a low-level call to fetch coefficients from a segment, but it deserves something more visible. I've just added a new method and released Skyfield version 2.9:

    >>> initial_epoch, interval_length, coefficients = segment.load_array()
    >>> print(coefficients.shape)

It's also mentioned in the updated docs:

https://pypi.org/project/jplephem/

Enjoy!

**Comment by brandon-rhodes** [comment]
(Oh, and, for the record, it was added in:)

7dae84d506edeccf81899ff5417448f4e4895161

**Comment by ChristopherRabotin** [comment]
Great thanks that was blazing fast!
