### ISSUE TITLE
spk.compute_and_differentiate yields incorrect body velocity

### ISSUE THREAD

**Issue by dsvinkin** [brandon-rhodes/python-jplephem#30]
I calculated the velosity of Earth Barycenter using jplephem v2.8 with the following code
```
from jplephem.spk import SPK
import numpy
kernel = SPK.open('de430.bsp')
jd = 2458502.4374 # 2019-01-18 80991.266 second of day (UT)
rEarth_bc, vEarth_bc = kernel[0,3].compute_and_differentiate(jd)  
vEarth_bc_abs = numpy.linalg.norm(vEarth_bc)*1e-5
```
and got velosity modulus vEarth_bc_abs of about 26.162 km/s which is inconsistent with the real value,
see the table below for comparison with Horizons (https://ssd.jpl.nasa.gov/horizons.cgi).

I have cheked the SPK.generate (called by SPK.compute_and_differentiate) function in jplephem/spk.py 
and found that the Chebyshev differentiation seems to be incorrect. 
The following code gives the velosity of Earth Barycenter consistent with Horizons values (the original code is commented and marked as #original):

  ```
    # Chebyshev differentiation.

    dT = empty_like(T)
    dT[0] = 0.0
    dT[1] = 1.0
    if coefficient_count > 2:
        dT[2] = twot1 + twot1
        for i in range(3, coefficient_count):
            #dT[i] = twot1 * dT[i-1] - dT[i-2] + T[i-1] + T[i-1] # original
            dT[i] = 2* (T[i-1] + t1 * dT[i-1]) - dT[i-2] # my
    
    #dT *= 2.0 # original
    #dT /= interval_length # original
    dT /= interval_length / 2 * 86400.0 # my, rates in km/s
    
    rates = (dT.T * coefficients).sum(axis=2)
    if scalar:
        rates = rates[:,0]
 
    yield rates
```

```
vEarth_bc km/s:             Vx                    Vy                    Vz                (Vx**2+Vy**2+Vz**2)**0.5
jplephem v 2.8:     -2.309729719622553E+01 -1.127415751194369E+01 -4.886930526926653E+00 26.1624512488775
Horizons:           -2.673298259309668E+01 -1.304879388205261E+01 -5.656169793123461E+00 30.280614868719987
jplephem corrected: -2.673298286600176E+01 -1.304879341660150E+01 -5.656169591350293E+00 30.280614871385986
```

**Comment by brandon-rhodes** [comment]
Could you verify that your code changes the differentiation that jplephem performs? I have checked the code both ways, and Python says that your expression is exactly the same as mine — it looks like you’ve just regrouped the terms and added some parentheses?

Without any edits to the package, if I run the script:

```
from jplephem.spk import SPK
kernel = SPK.open('de430t.bsp')
jd = 2458502.4374 # 2019-01-18 80991.266 second of day (UT)
rEarth_bc1, vEarth_bc1 = kernel[0,3].compute_and_differentiate(jd)
print(vEarth_bc1 / 86400.0)  # km/day -> km/sec
```

then I get:

```
[-26.73298259 -13.04879388  -5.65616979]
```

which are the same values you got from HORIZONS. Could you double-check to figure out where you got the three values `-2.309729719622553E+01 -1.127415751194369E+01 -4.886930526926653E+00`? I haven't worked out which `print()` statement I should add to your script to get those three numbers to print to my screen.

**Comment by brandon-rhodes** [comment]
Oh! I see — your `print` statement must have done something like this:

```
print(vEarth_bc / 1e-5)
```

But there are not 1e+5 seconds in a day, but slightly less, so your numbers come out a bit low.

I've just gone into the documentation and added the following paragraph:

```
The velocity will by default be distance traveled per day, in whatever
units for distance the ephemeris happens to use.  To get a velocity per
second, simply divide by the number of seconds in a day:

>>> velocity_per_second = velocity / 86400.0
>>> print(velocity_per_second)
[-4.21175999 23.37572912 10.8352983 ]
```

Is there anything else I should add to help users who get into your situation?

**Comment by dsvinkin** [comment]
Thanks a lot!
The problem was indeed in units of velocity.

**Comment by brandon-rhodes** [comment]
I'm glad your problem is resolved! Hopefully the example now in the documentation will help future users in their first foray into NASA ephemeris units.
