### ISSUE TITLE
Ephemeris query for Vesta and Ceres

### ISSUE THREAD

**Issue by shbhuk** [brandon-rhodes/python-jplephem#32]
Hi,
I want to use get_body_barycentric_posvel() for querying the ephemeris for Vesta, Ceres, and some other asteroids. 
Do I understand correct, that right now it can only be used for bodies listed by 
`solar_system_ephemeris.bodies`?

**Comment by brandon-rhodes** [comment]
I'm going to close this issue for now pending further information. Feel free to re-open if you return at any point with more to say about this issue. Thanks!
