### ISSUE TITLE
The conda-forge package for jplephem is out of date (v2.9 instead of v2.12)

### ISSUE THREAD

**Issue by EndlessDex** [brandon-rhodes/python-jplephem#38]
Not sure if this is the correct reporting forum for this...

I'm need to use skyfield on multiple user-level windows systems and anaconda env management is the simplest way to organize this. Want to be able to tell the end users, "Download anaconda and then create an env using this file". Currently skyfield reports an error due to an out of date jplephem.

The workaround is to force install jplephem with pip since the pypi repo is up to date, but this is not viable for my end users.

**Comment by EndlessDex** [comment]
Realize that the conda-forge distro is maintained by a different repo. Sorry!

**Comment by brandon-rhodes** [comment]
No problem! Here's a pull request someone seems to be working on that might update its version:
https://github.com/conda-forge/jplephem-feedstock/pull/18

**Comment by EndlessDex** [comment]
[conda-forge/jplephem-feedstock#19](https://github.com/conda-forge/jplephem-feedstock/pull/19)

Made my own PR to resolve the issue the other one had. Passing all tests now!
