### ISSUE TITLE
How to make a PR against pypi documentation?

### ISSUE THREAD

**Issue by nbelakovski** [brandon-rhodes/python-jplephem#42]
I'd like to make a note in the pypi documentation that the timestamp being used is the julian date. This wasn't obvious to me as I was diving into this and it's not immediately obvious from the (copious) SPICE documentation that this is the case. I don't see that documentation in this repo, is it updated manually or is there another repo where I could submit an edit?

**Comment by brandon-rhodes** [comment]
The `setup.py` file reads the PyPI long description from the module's docstring:

https://github.com/brandon-rhodes/python-jplephem/blob/078f95996f9a43ba92e199460f570b6670d79c1b/setup.py#L8

So you can just make a pull request against that docstring, and it will become the PyPI documentation on the next release:

https://github.com/brandon-rhodes/python-jplephem/blob/078f95996f9a43ba92e199460f570b6670d79c1b/jplephem/__init__.py#L3

**Comment by brandon-rhodes** [comment]
The PR is now merged!
