### ISSUE TITLE
Segments with same keys 

### ISSUE THREAD

**Issue by TuSKan** [brandon-rhodes/python-jplephem#45]
Hi, It's me again :) 

I sucessful loaded the file [de441.bsp](ftp://ssd.jpl.nasa.gov/pub/eph/planets/bsp/de441.bsp)
```python
File type DAF/SPK and format LTL-IEEE with 28 segments:
-3100015.50..2440432.50  Type 2  Venus Barycenter (2) -> Venus (299)
-3100015.50..2440432.50  Type 2  Mercury Barycenter (1) -> Mercury (199)
-3100015.50..2440432.50  Type 2  Earth Barycenter (3) -> Earth (399)
-3100015.50..2440432.50  Type 2  Earth Barycenter (3) -> Moon (301)
-3100015.50..2440432.50  Type 2  Solar System Barycenter (0) -> Sun (10)
-3100015.50..2440432.50  Type 2  Solar System Barycenter (0) -> Pluto Barycenter (9)
-3100015.50..2440432.50  Type 2  Solar System Barycenter (0) -> Neptune Barycenter (8)
-3100015.50..2440432.50  Type 2  Solar System Barycenter (0) -> Uranus Barycenter (7)
-3100015.50..2440432.50  Type 2  Solar System Barycenter (0) -> Saturn Barycenter (6)
-3100015.50..2440432.50  Type 2  Solar System Barycenter (0) -> Jupiter Barycenter (5)
-3100015.50..2440432.50  Type 2  Solar System Barycenter (0) -> Mars Barycenter (4)
-3100015.50..2440432.50  Type 2  Solar System Barycenter (0) -> Earth Barycenter (3)
-3100015.50..2440432.50  Type 2  Solar System Barycenter (0) -> Venus Barycenter (2)
-3100015.50..2440432.50  Type 2  Solar System Barycenter (0) -> Mercury Barycenter (1)
2440432.50..8000016.50  Type 2  Venus Barycenter (2) -> Venus (299)
2440432.50..8000016.50  Type 2  Mercury Barycenter (1) -> Mercury (199)
2440432.50..8000016.50  Type 2  Earth Barycenter (3) -> Earth (399)
2440432.50..8000016.50  Type 2  Earth Barycenter (3) -> Moon (301)
2440432.50..8000016.50  Type 2  Solar System Barycenter (0) -> Sun (10)
2440432.50..8000016.50  Type 2  Solar System Barycenter (0) -> Pluto Barycenter (9)
2440432.50..8000016.50  Type 2  Solar System Barycenter (0) -> Neptune Barycenter (8)
2440432.50..8000016.50  Type 2  Solar System Barycenter (0) -> Uranus Barycenter (7)
2440432.50..8000016.50  Type 2  Solar System Barycenter (0) -> Saturn Barycenter (6)
2440432.50..8000016.50  Type 2  Solar System Barycenter (0) -> Jupiter Barycenter (5)
2440432.50..8000016.50  Type 2  Solar System Barycenter (0) -> Mars Barycenter (4)
2440432.50..8000016.50  Type 2  Solar System Barycenter (0) -> Earth Barycenter (3)
2440432.50..8000016.50  Type 2  Solar System Barycenter (0) -> Venus Barycenter (2)
2440432.50..8000016.50  Type 2  Solar System Barycenter (0) -> Mercury Barycenter (1)
```
Note that the kernel have duplicated keys!
When I try to select from kernel the Earth Barycenter with pair (0,3), it give me the last one. I know that it is a normal behavior of *Python*.
When a dictionary have duplicate keys, it choose the last one
```python
>> d = {"a": [1, 2], "b": [3, 4], "a": [10,20]}
>> d["a"]
[10, 20]
```
The problem is when I using *astropy* with ephemeris = de441.bsp, it use your package to get coordinates, and it fails to select the first one.
```python
from astropy.time import Time
from astropy import coordinates as coord

coord.solar_system_ephemeris.set('bsp/de441.bsp')

coord.get_moon(Time("1950-03-26 17:00:00", format="iso")) # it fails
```
The problem occur in line 278, of file *solar_system.py* inside *coordinates* subpackage
```python
     for pair in kernel_spec:
            spk = kernel[pair]
...
```
Is this problem of the file de441.bsp ?

obs.: if you prefer, I can open this issue on astropy repo

**Comment by brandon-rhodes** [comment]
Wow! So even though from the outside it looks like one single file, on the inside the file is split into two segments just as though it were still two files "part 1" and "part 2".

What change are you suggesting could be made to the `jplephem` library that would get this working again and fix the problem?

Also, for context: what drove the choice of this particular ephemeris? What are your precision requirements? We might be able to satisfy your mission requirements with a smaller file.

**Comment by TuSKan** [comment]
I think this is a problem of the file de441.bsp, not a problem of the library. So, I'll not suggest any changes.

The context: I'm analysing triple conjunctions (Jupyter, Saturno) from 5 BC to 2050 AD and map into Hebrew calendar.

I'm looking into [*SPK MERGE*](https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/ug/spkmerge.html)  to create locally a simgle file without duplicate keys, but it need a *LEAPSECONDS_KERNEL*  (LSK file) and I don't now if exist for *de441*.

Any ideia?

**Comment by brandon-rhodes** [comment]
> The context: I'm analysing triple conjunctions (Jupyter, Saturno) from 5 BC to 2050 AD and map into Hebrew calendar.

My guess is that you can use an ephemeris like DE422 without any problem — it should show the same conjunctions. The biggest source of error in your estimates is not going to be planetary positions, but an estimate of the day on which each conjunction fell, because we don't know exactly which hour of the day each day started and ended in 5 BC. The relevant papers are linked here:

https://astro.ukho.gov.uk/nao/lvm/

**Comment by TuSKan** [comment]
Thank you very much for your suggestion and point out about the paper.
*SPKMERGE* gave me the same file (duplicated keys)
The file DE422 cover the period of context but gave one error in * jupyter*
```python
"jupyter's position cannot be calculated with the ../bsp/de422.bsp ephemeris."
```

**Comment by brandon-rhodes** [comment]
Where does that error come from? Usually you have to share a traceback before it can be fully diagnosed.

**Comment by TuSKan** [comment]
Sorry for that. I successful make it work.
Thak you very much for suport.
I'll back to my long journey

**Comment by brandon-rhodes** [comment]
I'm glad you were able to make it work! Thanks for following up.
