### ISSUE TITLE
Information on coordinate systems needed

### ISSUE THREAD

**Issue by avanc** [brandon-rhodes/python-jplephem#46]
This is not a real issue but more a question:
I want to get the position and velocities of planets and moons relative to solar system barycenter. The [pypi documentation](https://pypi.org/project/jplephem/) gives some very good hints. However, it seems that I have a misunderstanding of the coordinate system: As the orbits of e.g. mars and earth are more or less in a plane, I would expect to have at least one component of (x,y,z) magnitudes smaller than the others. However, the result proves me wrong:

    >>> position = kernel[0,4].compute(2457061.5)
    >>> print(position)
    [2.057e+08 4.251e+07 1.394e+07]

Any hint for documentation of the coordinate system would help. I could not get my head around [SPK Required Read](https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/FORTRAN/req/spk.html).

In addition, a hint how to chain kernels and calculate the velocity of any object with respect to the solar system barycenter  would be great. E.g. Solar System Barycenter (0) -> Earth Barycenter (3) -> Moon (301)

Sorry for posting it as issue, but I don't know where to raise this question.

**Comment by brandon-rhodes** [comment]
Each `.bsp` file has the right to use whatever coordinate system it wants, so the documentation for the particular kernel file is really the authority that would answer your question. The symptom you describe, however, is usually the result of looking at ICRS ("J2000") x,y,z coordinates, which are oriented to Earth's equator, not the plane of the planets' orbits. You will want to learn about coordinate rotations and turn them into ecliptic x,y,z coordinates if you want the small z coordinate you are expecting. An astronomy library like Skyfield or AstroPy would offer standard support for that transform.

Each kernel segment produces a vector and, per Descartes, you can add vectors: so you can add the vectors for `[0,3]` and `[3,301]` to produce the position of the Moon with respect to the Solar System barycenter.

I'll plan to add both of these points to the "Details of the API" bullet list in the main docs the next time there's a release!

**Comment by avanc** [comment]
@brandon-rhodes Thanks for the quick response.

Until now, I ignored Skyfield as my impression was, that it is just earth centric. Does skyfield.api.load not just load planets but also other information as barycenters? I'll have to dive deeper.

> Each kernel segment produces a vector and, per Descartes, you can add vectors: so you can add the vectors for [0,3] and [3,301] to produce the position of the Moon with respect to the Solar System barycenter.
But this does not apply for velocity? E.g. compute_and_differentiate()? Do I have to differentiate by hand (e.g. calculate to positions at slightly different time)?

**Comment by brandon-rhodes** [comment]
> Until now, I ignored Skyfield as my impression was, that it is just earth centric. Does skyfield.api.load not just load planets but also other information as barycenters? I'll have to dive deeper.

Skyfield lets you observe any location from any other location. Now that you mention it, I suppose there might not be any explicit documentation about creating or using a Solar System barycenter position. `ICRF([0,0,0])` I think does the job, but I'll take a look at the documentation tomorrow and make it explicit somewhere how to create that position — or maybe add a separate object for it if there isn't one already.

> But this does not apply for velocity? E.g. compute_and_differentiate()? Do I have to differentiate by hand (e.g. calculate to positions at slightly different time)?

Yes! It applies for velocity too; I read quickly and didn't see the word "velocity" your question. Add them together, you get out the combined velocity; they combine linearly.

**Comment by avanc** [comment]
@brandon-rhodes Can you point me to the documentation? I'm still stuck.

**Comment by brandon-rhodes** [comment]
Try reading this document:

From the center of the Solar System

**Comment by brandon-rhodes** [comment]
I'm going to close this issue, as it's not seen activity for more than a year and does not in any case describe a bug in jplephem. Please feel free to comment further on the closed issue if you have any further progress to share, though!
