### ISSUE TITLE
Expose version as __version__

### ISSUE THREAD

**Issue by pllim** [brandon-rhodes/python-jplephem#47]
Hello! Would be nice if downstream packages can check for `jplephem.__version__` instead of relying on the change log text within `__init__.py`. This could be accomplished using [setuptools_scm](https://pypi.org/project/setuptools-scm/) or other means as you see fit. Thanks!

xref astropy/astropy#11700

**Comment by brandon-rhodes** [comment]
Good idea! I've added it, and it should appear with the next release.

**Comment by pllim** [comment]
Thank you for the quick fix!
