### ISSUE TITLE
Ephemerides not pip-installable

### ISSUE THREAD

**Issue by Juanlu001** [brandon-rhodes/python-jplephem#7]
It's stated on the PyPI page of the package that the ephemerides can be installed using `pip install de421` but this is what I got:

```
$ pip install de421
Downloading/unpacking de421
  Could not find a version that satisfies the requirement de421 (from versions: 2008)
Cleaning up...
No distributions matching the version for de421
```

I can still follow the procedure you describe on the README but it's a bit more tedious. `pip install de421` is unbeatable :)

**Comment by brandon-rhodes** [comment]
I never went back and checked, but it looks like the issue that I opened was finally closed in June, and it looks like I am able to `pip install` all four PyPI-hosted ephemerides. We can finally close this issue!

**Comment by Juanlu001** [comment]
Great! It's never too late :)
